name: Build All (x64 Debug)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-2025
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore ScreenCover.sln

      - name: Build all projects (Debug x64)
        run: msbuild ScreenCover.sln /t:Build /p:Configuration=Debug /p:Platform=x64 /m

      - name: Upload all build outputs
        uses: actions/upload-artifact@v4
        with:
          name: BuildOutput-x64-Debug
          path: |
            **/x64/Debug/**
