name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

      - name: Find all build outputs
        id: find_outputs
        run: |
          echo "Looking for all bin/${{ env.BUILD_CONFIGURATION }} folders..."
          $outputs = Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse -Directory | Where-Object { $_.FullName -match "bin\\${{ env.BUILD_CONFIGURATION }}$" }
          $paths = $outputs | ForEach-Object { $_.FullName }
          echo "Found the following output folders:"
          $paths
          # 将路径传递给后续步骤
          echo "::set-output name=paths::$(($paths -join ';'))"
        shell: powershell

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BuildOutputs
          path: ${{ env.GITHUB_WORKSPACE }}/x64/${{ env.BUILD_CONFIGURATION }}

